import { ArrowRight, Bookmark, CheckCircle2, LogOut, Play, Trophy } from 'lucide-react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { useApp } from '../state/AppContext'

export function MyPage() {
  const { authReady, isLoggedIn, user, logout, favorites, summary, text } = useApp()
  const navigate = useNavigate()
  if (!authReady) return <div className="auth-loading">{text('正在读取学习记录…', '正在讀取學習記錄…')}</div>
  if (!isLoggedIn) return <Navigate to="/login?next=/my" replace />
  const seconds = Math.floor((summary?.continue_learning?.current_ms ?? 0) / 1000)
  const time = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`
  return <div className="my-page"><section className="my-hero"><div className="container"><span className="eyebrow">MY CANTOSCENE</span><h1>{text(`早晨，${user?.display_name ?? ''}。`)}</h1><p>{text('今天不用学很多，回来听懂一句就好。', '今天不用學很多，回來聽懂一句就好。')}</p></div></section><section className="section compact-top"><div className="container dashboard-grid"><div className="dashboard-main"><div className="continue-card"><span className="stamp stamp-peach">CONTINUE</span><h2>{summary?.continue_learning ? text('粤语对白练习', '粤語對白練習') : text('从第一段真实对白开始', '從第一段真實對白開始')}</h2><p>{summary?.continue_learning ? text(`上次学到 ${time}`, `上次學到 ${time}`) : text('边听边看字幕，收藏你想学会的句子。', '邊聽邊看字幕，收藏你想學會的句子。')}</p><Link className="btn btn-primary" to={`/watch/${summary?.continue_learning?.video_slug ?? 'cha-chaan-teng'}`}>{text(summary?.continue_learning ? '继续学习' : '开始学习', summary?.continue_learning ? '繼續學習' : '開始學習')}<ArrowRight /></Link></div><div className="recent-card"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>{text('学习内容', '學習內容')}</h2></div></div><Link to="/watch/cha-chaan-teng"><Play fill="currentColor" /><span><b>{text('粤语对白练习', '粤語對白練習')}</b><small>{text(`已开始 ${summary?.videos_started ?? 0} 段视频`, `已開始 ${summary?.videos_started ?? 0} 段影片`)}</small></span><ArrowRight /></Link><Link to="/courses"><CheckCircle2 /><span><b>{text('香港日常场景课程', '香港日常場景課程')}</b><small>{text(`已完成 ${summary?.lessons_completed ?? 0} 课`, `已完成 ${summary?.lessons_completed ?? 0} 課`)}</small></span><ArrowRight /></Link></div></div><aside className="dashboard-side"><div className="stat-card"><Trophy /><span><b>{summary?.lessons_completed ?? 0}</b><small>{text('完成课程', '完成課程')}</small></span></div><div className="stat-card"><Bookmark /><span><b>{favorites.length}</b><small>{text('收藏台词', '收藏台詞')}</small></span></div><Link className="saved-preview" to="/favorites"><span className="eyebrow">YOUR PHRASEBOOK</span><h3>{text('我的句子本')}</h3><p>{favorites.length ? text(`已经留下 ${favorites.length} 句真实粤语。`, `已經留下 ${favorites.length} 句真實粤語。`) : text('收藏第一句真实粤语吧。', '收藏第一句真實粤語吧。')}</p><span>{text('查看收藏', '查看收藏')} →</span></Link><button className="logout-button" onClick={() => { void logout().then(() => navigate('/')) }}><LogOut />{text('退出登录', '登出')}</button></aside></div></section></div>
}
