import { ArrowRight, Bookmark, CheckCircle2, LogOut, Play, Trophy } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useApp } from '../state/AppContext'

export function MyPage() {
  const { isLoggedIn, setLoggedIn, favorites, text } = useApp()
  if (!isLoggedIn) return <Navigate to="/login" replace />
  return <div className="my-page"><section className="my-hero"><div className="container"><span className="eyebrow">MY CANTOSCENE</span><h1>{text('早晨，继续听懂香港。', '早晨，繼續聽懂香港。')}</h1><p>{text('今天不用学很多，回来听懂一句就好。', '今天不用學很多，回來聽懂一句就好。')}</p></div></section><section className="section compact-top"><div className="container dashboard-grid"><div className="dashboard-main"><div className="continue-card"><span className="stamp stamp-peach">CONTINUE</span><h2>{text('茶餐厅点餐 · 第 2 课', '茶餐廳點餐 · 第 2 課')}</h2><p>{text('点餐时怎样说冷热、甜度和数量。', '點餐時怎樣說冷熱、甜度和數量。')}</p><div className="progress-track"><span style={{ width: '40%' }} /></div><small>2 / 5 LESSONS</small><Link className="btn btn-primary" to="/lessons/restaurant-2">{text('继续课程', '繼續課程')}<ArrowRight /></Link></div><div className="recent-card"><div className="section-heading"><div><span className="eyebrow">RECENT</span><h2>{text('最近学习', '最近學習')}</h2></div></div><Link to="/watch/cha-chaan-teng"><Play fill="currentColor" /><span><b>{text('第一次在茶餐厅点餐', '第一次在茶餐廳點餐')}</b><small>{text('影视学习 · 今天', '影視學習 · 今天')}</small></span><ArrowRight /></Link><Link to="/lessons/restaurant-1"><CheckCircle2 /><span><b>{text('在茶餐厅坐低', '在茶餐廳坐低')}</b><small>{text('场景课程 · 昨天', '場景課程 · 昨天')}</small></span><ArrowRight /></Link></div></div><aside className="dashboard-side"><div className="stat-card"><Trophy /><span><b>2</b><small>{text('完成课程', '完成課程')}</small></span></div><div className="stat-card"><Bookmark /><span><b>{favorites.length}</b><small>{text('收藏台词', '收藏台詞')}</small></span></div><Link className="saved-preview" to="/favorites"><span className="eyebrow">YOUR PHRASEBOOK</span><h3>{text('我的句子本', '我的句子本')}</h3><p>{favorites.length ? text(`已经留下 ${favorites.length} 句真实粤语。`, `已經留下 ${favorites.length} 句真實粵語。`) : text('收藏第一句真实粤语吧。', '收藏第一句真實粵語吧。')}</p><span>{text('查看收藏', '查看收藏')} →</span></Link><button className="logout-button" onClick={() => setLoggedIn(false)}><LogOut />{text('退出登录', '登出')}</button></aside></div></section></div>
}
